### ISSUE TITLE
Bigquery nodejs client fails behind corporate firewall

### ISSUE THREAD

**Issue by ashutoshdikshit** [googleapis/nodejs-bigquery#519] opened 2019-08-13 18:38 UTC
The bigquery nodejs client fails to connect to to the api when run on machine which is behind the corporate proxy. HTTP_PROXY and HTTPS_PROXY are set correctly. The bigquery command line tool works fine with the proxy setting in /etc/environment. 

Here is the error 

```
connect ETIMEDOUT 172.217.8.170:443
(node:19) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
```

**Comment by callmehiphop** [comment] 2019-08-13 21:54
@ashutoshdikshit would you be able to provide us with a small reproduction case? Thanks!

**Comment by ashutoshdikshit** [comment] 2019-08-13 22:33
@callmehiphop, Sure.  

This is what my code looks like. Let me know in case you need more information.

```
const winston = require("../logging/winston");
const BigQuery = require("@google-cloud/bigquery");
const fs = require("fs");
const bigquery = new BigQuery({
    projectId: "my_project_id",
    keyFilename: "fileName.json"
});
const path = require("path");

module.exports = {
    async v1GetDatasetMetadata(req, res) {
        try {
            const result = await bigquery.getDatasets();
            const dbNames = result[0].map(item => item.id);
            res.send(JSON.stringify(dbNames));
        } catch (error) {
            res.send(JSON.stringify(error));
        }
    }
};
```

And this is how the routes looks like 

```
router.get("/v1/dbMeta", (req, res) => {
    bqController.v1GetDatasetMetadata(req, res);
});
```

This is how this route is accessed : localhoost:3000/bq/v1/dbMeta and it returns all the datasets in bigquery. This works like a charm in machines which are not behind a proxy.

**Comment by ashutoshdikshit** [comment] 2019-08-22 16:45
Hi @JustinBeckwith @callmehiphop , is there a time frame for this bug to be fixed?

**Comment by callmehiphop** [comment] 2019-09-04 18:37
@ashutoshdikshit can you tell me what OS you're using and if you're on the latest version of the client? I'm attempting to reproduce locally (MacOS) but it seems to be working with proxies just fine.

**Comment by callmehiphop** [comment] 2019-09-04 18:45
Also it looks like the original error being reported is actually thrown from `express`, I would be curious to know what the actual contents of the response you're trying to send down are. Assuming the request fails and we're unable to stringify the `Error` object, it might contain additional information about why the request failed.

**Comment by ashutoshdikshit** [comment] 2019-09-04 20:55
@callmehiphop , here are the details 
Node Version : v12.8.0
Platform : Centos

Let me see how can I get the actual error message.

**Comment by callmehiphop** [comment] 2019-09-05 18:20
@ashutoshdikshit I think the error you're reporting comes explicitly from express. So maybe just logging the API error message? You might also consider not stringifying the entire Error object.

**Comment by callmehiphop** [comment] 2019-09-26 20:17
👋 @ashutoshdikshit haven't heard from you in a while, is this still an issue for you?

**Comment by callmehiphop** [comment] 2019-10-09 15:54
Hasn't been much activity here so I'm going to close this out, but please let us know if this was a mistake and this issue persists. Thanks!

**Closed by callmehiphop** 2019-10-09 15:54 UTC
Labels: needs more info, priority: p2, type: bug
