### ISSUE TITLE
schema default value current_timestamp() not containing milliseconds

### ISSUE THREAD

**Issue by philsch** [googleapis/nodejs-bigquery#1183] opened 2023-02-03 10:59 UTC
#### Environment details

  - OS: MacOS
  - Node.js version: v18.11.0
  - npm version: 8.19.2
  - `@google-cloud/bigquery` version: 6.1.0

#### Steps to reproduce

  1. Create a BigQuery table with a field `tstamp` that is of type `TIMESTAMP` and has a default value `current_timestamp()`
  2. Insert data without providing the timestamp value... if the data is inserted via the nodeJS SDK the timestamp does never contain milliseconds

#### Current behavior

Inserting data using the BigQuery Web Console:
```sql
INSERT INTO `<table>` (field1, field2) VALUES ("test","123")
```

The not provided `tstamp` when retrieved contains milliseconds, e.g. `2023-02-03 10:48:06.683620 UTC` .

Inserting the data with the NodeJS SDK like:
```js
const BigQuery = require('@google-cloud/bigquery').BigQuery

const instance = new BigQuery({
    project: 'project',
    location: 'EU',
})
const table = instance.dataset('dataset').table('table')

table.insert({
    field1: 'test',
    field2: '123'
})
```

The not provided field `tstamp` does not contain milliseconds, e.g. `2023-02-03 10:39:03 UTC`. I've checked this directly in the BigQuery Web Console and double checked by extracting `extract(millisecond FROM tstamp) as milli` in the SELECT statement.

#### Expected behavior

The field `tstamp` contains milliseconds, when the field is not provided when inserting data via code and the default value applies. 

#### Screenshot of both added values

![Screenshot 2023-02-03 at 11 58 04](https://user-images.githubusercontent.com/5527838/216586871-a24fea25-bd01-49b0-b7e9-11f6f73e0ea1.png)

**Comment by alvarowolfx** [comment] 2023-05-22 17:58
I managed to reproduce the issue here and it is not related to NodeJS specifically, as I managed to reproduce using the Go SDK. Seems to be an issue on the BQ insertAll API. I started some internal discussions here and will provide more details as when possible.

**Comment by alvarowolfx** [comment] 2023-06-01 17:51
The issue is now fixed on the BigQuery API side of things. @philsch thanks for the report.

**Closed by alvarowolfx** 2023-06-01 17:51 UTC
Labels: priority: p2, type: bug, api: bigquery
